#!/bin/bash

if [[ $# -ne 3 ]]; then 
	echo "Uso: ./sussing2NDfield_ascii inputfile BoxSize outputfile"
	exit 
fi

echo "WARNING: Copiando posiciones de halos principales y satélites."

echo "ANDFIELD COORDS" > $3

# Contamos el numero de lineas:
nl=$(( $(wc -l < $1) - 1))

echo "[3 ${nl}]" >> $3
echo "# Generated by sussing2NDfield.sh, $(date), @$(hostname)" >> $3
echo "BBOX [0,0,0] [$2,$2,$2]" >> $3

awk 'NR > 1 {print $6, $7, $8}' $1 >> $3

echo "Done!"

