#!/bin/bash

if [[ $# -ne 3 ]]; then 
	echo "Uso: ./sussing2NDfield_ascii inputfile BoxSize outputfile"
	exit 
fi

echo "WARNING: Copiando posiciones de halos principales y satélites."

echo "ANDFIELD COORDS" > $3

# Contamos el numero de lineas:
nf=$(awk 'BEGIN {c=0} NR>1 && $7<=850000 {c=c+1} END {print c}' $1)
nl=$(( $(wc -l < $1) - 1 - $nf))

echo "[3 ${nl}]" >> $3
echo "# Generated by sussing2NDfield.sh, $(date), @$(hostname)" >> $3
echo "BBOX [0,0,0] [$2,$2,$2]" >> $3

awk 'NR > 1 && $7 > 850000 {print $6, $7, $8}' $1 >> $3

echo "Done!"

